services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file: jellyfin.env
    volumes:
      - ./jellyfin/library:/config
      - ./jellyfin/tvseries:/data/tvshows
      - ./jellyfin/movies:/data/movies
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      proxy:
    ports:
      # Wichtige Ports für lokale Erkennung und DLNA
      - "8096:8096"  # HTTP
      - "8920:8920"  # HTTPS
      - "7359:7359/udp"  # Service Discovery
      - "1900:1900/udp"  # DLNA
    labels:
      # Basis-Konfiguration
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      
      # Router Konfiguration
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=http_resolver"
      
      # Service Konfiguration
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      
      # Middleware Chain - ANGEPASST für Jellyfin
      - "traefik.http.routers.jellyfin.middlewares=default@file,admin-whitelist@file"
      
      # Sticky Sessions für Streaming
      - "traefik.http.services.jellyfin.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.jellyfin.loadbalancer.sticky.cookie.secure=true"
    restart: always

networks:
  proxy:
    external: true
